### ISSUE TITLE
enterNextRow is not working

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-grid-pro#102]
Steps to reproduce:
1) Go to https://cdn.vaadin.com/vaadin-grid-pro/2.0.3/demo/#grid-pro-edit-column-demos and scroll down to the "Use Enter to Focus Next Row" section.
2) Double click on one of the first names and edit the text
3) Press ENTER

Expected behavior: focus should move the selection down one row and remain in edit mode.

Actual behavior: selection moves down one row, and then it returns back up to the cell I just edited. Also it exits edit mode.

Browser: Firefox and Chrome.

Seems a regression from: https://github.com/vaadin/vaadin-grid-pro/pull/100

**Comment by web-padawan** [comment]
Confirmed. A proper fix in this case would be to prevent `vaadin-grid` keyboard handler from being called when we switch cell while entering next row. Will also need to improve tests to catch this.

**Comment by RockyMM** [comment]
Is this deployed to https://vaadin.com/components/vaadin-grid-pro/java-examples? For me Enter key is still misbehaving.

**Comment by web-padawan** [comment]
At the moment, https://vaadin.com is not running latest version (14.0.9) where the bug is fixed.
That's why the demos are not working there. The website team will take care of updating soon.
