### ISSUE TITLE
Demo: Custom Editor Type is not working on Examples page

### ISSUE THREAD

**Issue by RockyMM** [vaadin/vaadin-grid-pro#105]
On the [Examples](https://vaadin.com/components/vaadin-grid-pro/java-examples) page, go to Custom Editor Type and double click on any email in the grid. Instead of editor, what happens is that only the cell is cleared of the value. Upon navigating to a different cell, the old value is put back

**Comment by web-padawan** [comment]
Seems like this was fixed at some point.

![gridpro](https://user-images.githubusercontent.com/10589913/74529809-45b98780-4f31-11ea-8014-bdc97abf9ad1.gif)

**Comment by RockyMM** [comment]
I confirm it is fixed. Though, upon further testing I noticed some issues in FireFox; which I will report in new bug reports.
