### ISSUE TITLE
Vaadin GridPro: “TypeError: Cannot read property 'localName' of undefined”

### ISSUE THREAD

**Issue by lipisak** [vaadin/vaadin-grid-pro#117]
I am getting error mentioned in title when anyone clicks on any component in detail shown in grid-pro.

This error with more information is also mentioned here: https://stackoverflow.com/questions/59199178/vaadin-gridpro-typeerror-cannot-read-property-localname-of-undefined

This happend only with grid-pro not with grid

**Comment by appshare1603** [comment]
Hi Vaadin,
same problem and extremely annoying.
This is a major bug and should be fixed

see here: https://vaadin.com/forum/thread/18276688/gridpro
- and no comments

**Comment by tomivirkki** [comment]
Sorry for the delay, fix in https://github.com/vaadin/vaadin-grid-pro/pull/123

**Comment by lipisak** [comment]
Great! Thanks

**Comment by appshare1603** [comment]
Thank you !!!
