### ISSUE TITLE
Custom Editor Type is not working with Firefox

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/vaadin-grid-pro#120]
The Custom Editor Type example on Grid Pro is not working at all with Firefox. 

- Open https://vaadin.com/components/vaadin-grid-pro/java-examples in Firefox
- Scroll down to the “Custom Editor Type” example
- Edit an email in the grid. 
- The changes aren’t sticking.

Also reproduced in Vaadin 14.1.27

**Comment by cmrgKoradir** [comment]
Probably worth mentioning that the changes _are_ sticking if you "confirm" by clicking outside the cell, rather than with `tab` or `enter`.

**Comment by javier-godoy** [comment]
Duplicate of https://github.com/vaadin/vaadin-grid-pro-flow/issues/94

**Comment by web-padawan** [comment]
Closing as duplicate per above comment.
