### ISSUE TITLE
Selection column not rendered in 18.0.3

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-grid-pro#155]
To reproduce:
1. Download https://start.vaadin.com/?preset=list-view
2. `mvn`

The Java view shows no selection checkboxes
When you navigate to the javahtml view you see checkboxes
If you refresh on the javahtml view, you see no checkboxes
If you navigate back to the Java view, you see checkboxes

The typescript view works as expected

**Comment by yuriy-fix** [comment]
The issue was caused by https://github.com/vaadin/vaadin-flow-components/commit/8b5b88893fdf1954ee4eadf83c262d560a0415e6. It was reverted with https://github.com/vaadin/vaadin-flow-components/commit/7391d701aaa5c6ee9aa3c69d90080c64de8efe4d.
