### ISSUE TITLE
Cannot use editModeRenderer with lit-html `render` function

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-grid-pro#164]
Current demo shows how to add a custom editor imperatively, something like:

```ts
root.innerHTML = '';
const datePicker = document.createElement('vaadin-date-picker');
datePicker.value = (model?.item as Person).birthday;
root.appendChild(datePicker);
```

Ideally, that could be done declaratively with `render` and `html` from `lit-html`:

```ts
const person = model?.item as Person
render(html`<vaadin-date-picker .value=${person.birthday}></vaadin-date-picker>`, root);
```

But this approach works only for the first time the cell enters edit mode.

On my investigation, it seems that the current implementation of Grid Pro is incompatible with how `render` works.

`render(result, container)` when called for the first time for some `container` will add an entry for this node to its internal `WeakMap` and add two comments tags as children and keep track of the references as `startNode` and `endNode` (see image below). They are then used to attach `result` relative to them.
On the following calls to `render` for the same `container`, it will first get the entry from the `WeakMap` and then proceed with its logic to attach `result`.

<img width="423" alt="Screenshot 2021-02-23 at 9 54 57" src="https://user-images.githubusercontent.com/262432/108851008-bc687680-75c2-11eb-865a-514974f664e5.png">

What makes Grid Pro incompatible with this, is that when the cell exits edit mode, it will clear the cell content and attach the other content (eg. a plain text). That essentially removes the comments tags markers added by `render` and the next time the user tries to enter edit mode for that cell, this check will be done and nothing will be attached:

```js
if (this.startNode.parentNode === null) {
  return;
}
```

There could be two solutions that I can think of for this limitation:

* Make `Grid Pro` (or maybe `Grid` 🤔) uses `render` and `html` to attach the cell content and recommend this approach for custom renderers (not sure how it would work for the Flow counterpart, though)
* Somehow keep the cell content on edit mode saved and reattach it before calling the renderer (could have a performance impact since it could potentially double the amount of DOM manipulation)

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/web-components/issues/366
