### ISSUE TITLE
Make Tab and Shift Tab switching editable cell an opt-in behavior

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-grid-pro#17]
As discussed in person, there should be a way for users to keep the same <kbd>Tab</kbd> / <kbd>Shift</kbd> + <kbd>Tab</kbd> behavior as in `vaadin-grid`: step out of content footer (out of grid, if there is no footer)  / step to header.

The native behavior is aligned with [ARIA Best Practices](https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html#ex2_label) and has been tested with screen readers.

New behavior implemented in #8 (focusing next / previous editable cell) will cause a breaking change, from the point of view of existing `vaadin-grid` users, and will make keyboard navigation confusing.

This is a bit tricky because currently `_onTabKeyDown` in `Vaadin.Grid.KeyboardNavigationMixin `
 is assuming that the `e.composedPath()[0]` is a cell content, not a focusable inside it:
https://github.com/vaadin/vaadin-grid/blob/c641482feee3dfbe5ae3e5e62208715c9b4739da/src/vaadin-grid-keyboard-navigation-mixin.html#L377

**Comment by jouni** [comment]
This issue seems outdated.

**Comment by web-padawan** [comment]
Thanks. I'm closing this, let's reconsider if we receive some feedback from the users.
