### ISSUE TITLE
Ensure a11y of the edit column feature

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid-pro#4]
child of https://github.com/vaadin/vaadin-core/issues/211

Make sure the new edit column feature is usable with keyboard and screen readers

**Comment by web-padawan** [comment]
Discussed in person and agreed to test all the 3 editor types with VoiceOver utility for now.
Will report findings in the comment below and submit PR in case some fixes are necessary.

**Comment by web-padawan** [comment]
Confirmed that text, select and checkbox are recognised by VoiceOver in Chrome and Safari.
There are slight differences in how the current item in the select is read, especially in Safari the checkmark seems to be pronounced (it shouldn't be) but that's not a grid issue.
