### ISSUE TITLE
Polish the cell editor appearance

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-grid-pro#5]
child of https://github.com/vaadin/vaadin-core/issues/211

- Work with designers to make sure the column editor appearance is as expected on Lumo & MD

**Comment by web-padawan** [comment]
Basic Lumo styling done in #8 , needs to be verified. Material to be implemented

**Comment by web-padawan** [comment]
Updated the styling in scope of #24 relying on `pro-grid-editor` theme setting there.
Will add some notes in that PR.
